# -*- coding: utf-8 -*-
"""Rock-Paper-Scissor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeNLFeRtA_WPWChdnoUi8wWCYuM_nt67

# **AINE AI - VIP SEPTEMBER 2021**

#**Project 5: Essentials of Python Programming**
# Aim: Developing **‘Rock, Paper and Scissors’** game using Python programming

# Objectives:
1. Understand the environment of the Jupyter Notebook on Anaconda 3.
2. Using different cells and comments in the notebook to mention explanations of
your program and syntaxes.
3. Understanding basic data types and lists in Python.
4. Working with lists and accessing its elements.
5. Taking user inputs and printing them.
6. Working on the random library
7. Initializing the value of a variable
8. Creating loops asking the play the game multiple times unless the user enters Q
9. Using conditional operators to play the game with different options in different
games.

# By - Divya Janani.S
"""

# import random library
import random

# Print multiline instruction
# performstring concatenation of string
print("Winning Rules of the Rock paper scissor game as follows: \n"
                                +"Rock vs paper->paper wins \n"
                                + "Rock vs scissor->Rock wins \n"
                                +"paper vs scissor->scissor wins \n")
while True:
    user_action = input("Enter a choice (rock, paper, scissors): ")        # taking input from the user
    possible_actions = ["rock", "paper", "scissors"]                       # creating a list
    computer_action = random.choice(possible_actions)                      # initialising the variable and accessing elements from the list
    print(f"\nYou chose {user_action}, computer chose {computer_action}.\n")

    if user_action == computer_action:
        print(f"Both players selected {user_action}. It's a tie!")
    elif user_action == "rock":
        if computer_action == "scissors":
            print("Rock smashes scissors! You win!")                  # using conditional statements to determine the winner of the game
        else:
            print("Paper covers rock! You lose.")
    elif user_action == "paper":
        if computer_action == "rock":
            print("Paper covers rock! You win!")
        else:
            print("Scissors cuts paper! You lose.")
    elif user_action == "scissors":
        if computer_action == "paper":
            print("Scissors cuts paper! You win!")
        else:
            print("Rock smashes scissors! You lose.")
    print("Do you want to play again? (Y/N)")                         
    ans = input()
  
    # if user input n or N then condition is True
    if ans == 'n' or ans == 'N':
        break
      
# after coming out of the while loop
# we print thanks for playing
print("\nThanks for playing")